config/routes.rb
Rails.application.routes.draw do
  resources :follows
  resources :restaurants
  resources :comments
  resources :posts
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root 'users#index'
  root "static_pages#home"
  get  "/signup",  to: "users#new"
  get  "/about",   to: "static_pages#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :post_id, presence: true 
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 10000}
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
    belongs_to :following, foreign_key: 'following_id', class_name: 'User'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  belongs_to :restaurant 


  validates :content, presence: true, length: {maximum: 10000}
  validates :user_id, presence: true
  validates :restaurant_id, presence: true 
  


end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :posts

  validates :name, presence: true, length: {maximum: 100}
  validates :location, presence: true, length: {maximum: 100}
  validates :price_range, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments

  has_many :follows

  # Allows association to view list of users who follow a given user i.e. user.followers
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  # Allows association to view list of users who follow a given user i.e. user.following
  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followings, through: :following_relationships, source: :following

  validates :name,  presence: true, length: {maximum: 100}
  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #validates :email, presence: true, length: {maximum: 200}, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :age, presence: true
  validates :bio, presence: true, length: {maximum: 1000} 




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
  
    def help
    end
  
    def about
    end
  
    def contact
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :bio, :age, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag("logo2.png", width:"200"), root_path, id:"logo"%>   
     
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "About",    about_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="container-fluid row">
  <div class="col-md-8 home-left">
    <%= image_tag "logo.png", width: "400", class: "center-block" %>
  </div>  
  <div class="col-md-4 home-right">
    <%= form_with(url: about_path, scope: :session) do |f| %>
      <%= f.email_field :email, class: "form-control", placeholder: "Enter email"%>
      <%= f.password_field :password, class: "form-control", placeholder: "Enter password"%>
      <%= f.submit "Log in", class: "btn btn-warning btn-large btn-block btn-primary"%>
    <% end %>
    <hr/>
    <%= button_to "Sign up", signup_path, id: "open-contacts-dialog-btn",
      class: "btn btn-success btn-large btn-block btn-primary", method: "get" %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder: "name" %>
  </div>

  <div>
    <%= form.text_area :bio, placeholder: "bio"  %>
  </div>

  <div>
    <%= form.number_field :age, placeholder: "age"  %>
  </div>

  <div>
    <%= form.text_field :email, placeholder: "email"  %>
  </div>

  <div>
    <%= form.text_field :password, placeholder: "password"  %>
  </div>

  <div>
    <%= form.submit "Sign up", class: "btn btn-success btn-large btn-block btn-primary"%>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= user.bio %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= user.age %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<div class="container-fluid row">

  
  <div class="col-md-5 col-md-offset-4">
    <h1>Sign up<br/><small>It's quick and easy.</small></h1>
    <%= render "form", user: @user %>
  </div>
  <br>

</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>